# Generated by Django 5.0.7 on 2024-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(default='sayliborole29@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='name',
            field=models.CharField(default='sayli', max_length=100),
            preserve_default=False,
        ),
    ]
