# Generated by Django 5.0.7 on 2024-07-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_servicerequest_email_servicerequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='upload',
            field=models.FileField(default='E:\\Downloads\\Backend _ Django Problem Statement Case Study.pdf', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
